#!/usr/bin/env python3
"""plan_progress.py — progress + stall block generator for project-plan markdown.

SINGLE LOGICAL OWNER. This script owns exactly TWO marked regions of the target
file and nothing else:

  1. The progress block (human-readable), near the top:
       <!-- progress:start -->  ...  <!-- progress:end -->
  2. The task-state log (machine-readable JSON), at the bottom:
       <!-- progress-state:start -->  ...  <!-- progress-state:end -->

Everything outside those two regions is READ-ONLY. The script parses the file to
compute metrics and run structural checks, but never mutates anything except its
two regions. Validation problems are emitted as warnings, never auto-fixed.

Stall timing comes from the in-file state log, NOT from git
--------------------------------------------------------------
git blame is only a flagpole ("when did this *line* last change"), and a
squash-per-phase workflow collapses every task line in a phase to one timestamp,
destroying per-task granularity. Instead, on each run the script diffs current
task *status* against the status it recorded last time and stamps `since` only
when the status actually changes. Stall age = today - since. This:
  * survives history rewrites / squashes (the blob is the source of truth),
  * needs no git and works offline,
  * measures status change, not file edits (reformatting a line is not progress).

Status is derived from the checkbox plus inline markers and is one of:
  done · cancelled · deferred · blocked · in_progress · open
A task whose detail text contains "deferred" -> deferred (silent, never flagged).
A task whose detail text contains "blocked"  -> blocked (shown in its own bucket,
with its own age, because a dependency wait is a different signal than a forgotten
task). open / in_progress in scope and older than the threshold -> stalled.

Usage
-----
    python scripts/plan_progress.py PLAN.md                # update both regions + warn
    python scripts/plan_progress.py PLAN.md --print        # print progress block; don't write
    python scripts/plan_progress.py PLAN.md --check        # don't write; exit 1 if stale / warnings
    python scripts/plan_progress.py PLAN.md --no-stall     # skip stall logic; leave state log untouched
    python scripts/plan_progress.py PLAN.md --seed-from-git # bootstrap `since` from git blame on first sight
    python scripts/plan_progress.py PLAN.md --threshold 3

Stdlib only. No third-party dependencies.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta

START = "<!-- progress:start -->"
END = "<!-- progress:end -->"
STATE_START = "<!-- progress-state:start -->"
STATE_END = "<!-- progress-state:end -->"
GEN_NOTE = (
    "<!-- Auto-generated by scripts/plan_progress.py — do not edit inside these "
    "markers. Regenerate: python scripts/plan_progress.py <file> -->"
)
STATE_NOTE = (
    "<!-- Task-state log for the stall meter — auto-generated, do not edit by hand. "
    "`since` is the date each task last changed status. -->"
)
STATE_VERSION = 1

CHECKBOX_RE = re.compile(r"^(?P<indent>\s*)- \[(?P<state>[ xX/\-])\]\s+(?P<text>.*\S)\s*$")
PHASE_RE = re.compile(r"^##\s+Phase\s+(?P<num>\d+)\s*[-\u2013\u2014]\s*(?P<title>.+?)\s*$")
SUBHEADER_RE = re.compile(r"^###\s+")
H2_RE = re.compile(r"^##\s+")
HEADER_RE = re.compile(r"^(#{1,6})\s+(?P<title>.+?)\s*$")
FRONTMATTER_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
BARE_CHECKBOX_RE = re.compile(r"\[[ xX/\-]\]")
PROPER_CHECKBOX_PREFIX_RE = re.compile(r"^\s*- \[[ xX/\-]\]")

DONE = "done"
OPEN = "open"
IN_PROGRESS = "in_progress"
CANCELLED = "cancelled"
_STATE_MAP = {" ": OPEN, "x": DONE, "X": DONE, "/": IN_PROGRESS, "-": CANCELLED}


@dataclass
class Task:
    text: str
    state: str
    line_no: int
    deferred: bool
    blocked: bool
    phase_num: int


@dataclass
class Phase:
    num: int
    title: str
    tasks: list[Task] = field(default_factory=list)

    @property
    def counted(self) -> list[Task]:
        return [t for t in self.tasks if t.state != CANCELLED]

    @property
    def done(self) -> int:
        return sum(1 for t in self.counted if t.state == DONE)

    @property
    def total(self) -> int:
        return len(self.counted)

    @property
    def is_closed(self) -> bool:
        return self.total == 0 or self.done == self.total


@dataclass
class Stall:
    phase_num: int
    text: str
    bdays: int


@dataclass
class Metrics:
    done: int
    total: int
    phases_closed: int
    phases_total: int
    active_phase: Phase | None

    @property
    def task_pct(self) -> int:
        return 0 if self.total == 0 else round(self.done * 100 / self.total)


def task_key(text: str) -> str:
    """Stable key for a task. Case preserved; rewording a task resets its clock
    (same caveat that applied to git-blame matching). Add a trailing {#id} later
    if you need a key that survives rewrites."""
    return text.strip()


def derive_status(task: Task) -> str:
    if task.state == CANCELLED:
        return CANCELLED
    if task.state == DONE:
        return DONE
    if task.deferred:
        return "deferred"
    if task.blocked:
        return "blocked"
    if task.state == IN_PROGRESS:
        return IN_PROGRESS
    return OPEN


# ----------------------------------------------------------------------------- parsing


def parse_phases(lines: list[str]) -> list[Phase]:
    phases: list[Phase] = []
    cur: Phase | None = None
    in_qa = False
    for idx, raw in enumerate(lines):
        pm = PHASE_RE.match(raw)
        if pm:
            cur = Phase(num=int(pm.group("num")), title=pm.group("title").strip())
            phases.append(cur)
            in_qa = False
            continue
        if H2_RE.match(raw):
            cur = None
            in_qa = False
            continue
        if cur is None:
            continue
        if SUBHEADER_RE.match(raw):
            in_qa = True
            continue
        if in_qa:
            continue
        cm = CHECKBOX_RE.match(raw)
        if cm:
            text = cm.group("text").strip()
            detail = _collect_detail(lines, idx)
            blob = (text + " " + detail).lower()
            cur.tasks.append(
                Task(
                    text=text,
                    state=_STATE_MAP[cm.group("state")],
                    line_no=idx + 1,
                    deferred="deferred" in blob,
                    blocked="blocked" in blob,
                    phase_num=cur.num,
                )
            )
    return phases


def _collect_detail(lines: list[str], idx: int) -> str:
    out = []
    for raw in lines[idx + 1 :]:
        if not raw.strip():
            break
        if CHECKBOX_RE.match(raw):
            break
        if raw[:1] in (" ", "\t"):
            out.append(raw.strip())
        else:
            break
    return " ".join(out)


def parse_frontmatter_block(text: str) -> tuple[str, int]:
    m = FRONTMATTER_RE.match(text)
    return (text[: m.end()], m.end()) if m else ("", 0)


def parse_priority_order(frontmatter: str) -> list[str]:
    items, capturing = [], False
    for raw in frontmatter.split("\n"):
        if re.match(r"^priority_order:\s*$", raw):
            capturing = True
            continue
        if capturing:
            m = re.match(r"^\s+-\s+(.*\S)\s*$", raw)
            if m:
                items.append(m.group(1).strip())
            elif raw.strip() and not raw.startswith(" "):
                break
    return items


# ----------------------------------------------------------------------------- metrics


def compute_metrics(phases: list[Phase]) -> Metrics:
    done = sum(p.done for p in phases)
    total = sum(p.total for p in phases)
    closed = [p for p in phases if p.is_closed]
    incomplete = sorted((p for p in phases if not p.is_closed), key=lambda p: p.num)
    return Metrics(done, total, len(closed), len(phases), incomplete[0] if incomplete else None)


# ----------------------------------------------------------------------------- state log (in-file)


STATE_BLOCK_RE = re.compile(re.escape(STATE_START) + r".*?" + re.escape(STATE_END), re.DOTALL)
_JSON_FENCE_RE = re.compile(r"```json\s*(.*?)\s*```", re.DOTALL)


def load_state_blob(text: str) -> dict:
    m = STATE_BLOCK_RE.search(text)
    if not m:
        return {}
    body = m.group(0)
    fence = _JSON_FENCE_RE.search(body)
    payload = fence.group(1) if fence else body
    try:
        data = json.loads(payload)
        return data if isinstance(data, dict) else {}
    except (json.JSONDecodeError, ValueError):
        return {}


def update_state(prior: dict, phases: list[Phase], today: str, seed: dict | None) -> dict:
    prior_tasks = prior.get("tasks", {}) if isinstance(prior, dict) else {}
    new: dict[str, dict] = {}
    for phase in phases:
        for task in phase.tasks:
            key = task_key(task.text)
            status = derive_status(task)
            p = prior_tasks.get(key)
            if p and p.get("status") == status:
                since = p.get("since", today)
            elif p is None and seed is not None and key in seed:
                since = datetime.fromtimestamp(seed[key]).date().isoformat()
            else:
                since = today
            new[key] = {"status": status, "since": since}
    return new


def render_state_blob(state_tasks: dict, today: str) -> str:
    payload = {"version": STATE_VERSION, "updated": today, "tasks": state_tasks}
    body = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False)
    return "\n".join([STATE_START, STATE_NOTE, "```json", body, "```", STATE_END])


def splice_state_blob(text: str, block: str) -> str:
    if STATE_BLOCK_RE.search(text):
        return STATE_BLOCK_RE.sub(lambda _m: block, text, count=1)
    return text.rstrip("\n") + "\n\n" + block + "\n"


# ----------------------------------------------------------------------------- git seed (optional)


def git_context(path: str) -> tuple[str, str] | None:
    d = os.path.dirname(os.path.abspath(path)) or "."
    try:
        top = subprocess.run(
            ["git", "-C", d, "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if top.returncode != 0:
        return None
    repo = top.stdout.strip()
    return repo, os.path.relpath(os.path.abspath(path), repo)


def git_seed_dates(path: str) -> dict[str, int] | None:
    """task_key -> most recent author epoch in HEAD. Used only to bootstrap
    `since` on first sight of a task; never the ongoing source of truth."""
    ctx = git_context(path)
    if ctx is None:
        return None
    repo, rel = ctx
    try:
        out = subprocess.run(
            ["git", "-C", repo, "blame", "--line-porcelain", "HEAD", "--", rel],
            capture_output=True, text=True, timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    dates: dict[str, int] = {}
    cur_time: int | None = None
    for line in out.stdout.split("\n"):
        if line.startswith("author-time "):
            cur_time = int(line.split(" ", 1)[1])
        elif line.startswith("\t"):
            cm = CHECKBOX_RE.match(line[1:].rstrip())
            if cm and cur_time is not None:
                key = task_key(cm.group("text"))
                if key not in dates or cur_time > dates[key]:
                    dates[key] = cur_time
            cur_time = None
    return dates


# ----------------------------------------------------------------------------- stalls


def business_days_between(d0: date, d1: date) -> int:
    if d1 <= d0:
        return 0
    days, cur = 0, d0 + timedelta(days=1)
    while cur <= d1:
        if cur.weekday() < 5:
            days += 1
        cur += timedelta(days=1)
    return days


def compute_stalls(
    phases: list[Phase], metrics: Metrics, state_tasks: dict, threshold: int
) -> tuple[list[Stall], list[Stall]]:
    today = date.today()
    active = metrics.active_phase.num if metrics.active_phase else None
    stalled: list[Stall] = []
    blocked: list[Stall] = []
    seen: set[str] = set()
    for phase in phases:
        for task in phase.tasks:
            key = task_key(task.text)
            if key in seen:
                continue
            st = state_tasks.get(key)
            if not st:
                continue
            try:
                since = date.fromisoformat(st["since"])
            except (KeyError, ValueError):
                continue
            bdays = business_days_between(since, today)
            status = st.get("status")
            if status == "blocked":
                if bdays > threshold:
                    seen.add(key)
                    blocked.append(Stall(task.phase_num, task.text, bdays))
            elif status in (OPEN, IN_PROGRESS):
                in_scope = (task.phase_num == active) or (status == IN_PROGRESS)
                if in_scope and bdays > threshold:
                    seen.add(key)
                    stalled.append(Stall(task.phase_num, task.text, bdays))
    stalled.sort(key=lambda s: (s.phase_num, -s.bdays))
    blocked.sort(key=lambda s: (s.phase_num, -s.bdays))
    return stalled, blocked


# ----------------------------------------------------------------------------- render


def bar_str(pct: int, width: int = 20) -> str:
    filled = max(0, min(width, round(pct / 100 * width)))
    return "\u2588" * filled + "\u2591" * (width - filled)


def render_block(
    metrics: Metrics, stalled: list[Stall], blocked: list[Stall], do_stall: bool, threshold: int
) -> str:
    pct = metrics.task_pct
    active = metrics.active_phase
    active_label = f"Phase {active.num} \u2014 {active.title}" if active else "\u2014 all phases closed"
    lines = [
        START,
        GEN_NOTE,
        f"**Progress:** {bar_str(pct)} **{pct}%**",
        (
            f"**Tasks:** {metrics.done}/{metrics.total} \u00b7 "
            f"**Phases closed:** {metrics.phases_closed}/{metrics.phases_total} \u00b7 "
            f"**Active:** {active_label} \u00b7 "
            f"**Updated:** {date.today().isoformat()}"
        ),
        "",
    ]
    if not do_stall:
        lines.append("_Stall check disabled (--no-stall)._")
    elif not stalled and not blocked:
        lines.append(f"_\u2713 Nothing stalled or blocked (threshold: {threshold} business days)._")
    else:
        if stalled:
            lines.append(f"**\u26a0 Stalled (> {threshold} business days):**")
            for s in stalled:
                lines.append(
                    f"- **Phase {s.phase_num}** \u00b7 {s.text.rstrip(':')} \u2014 _open {s.bdays} business days_"
                )
        if blocked:
            lines.append(f"**\u23f3 Blocked (> {threshold} business days):**")
            for s in blocked:
                lines.append(
                    f"- **Phase {s.phase_num}** \u00b7 {s.text.rstrip(':')} \u2014 _blocked {s.bdays} business days_"
                )
    lines.append(END)
    return "\n".join(lines)


def splice_block(text: str, block: str) -> str:
    existing = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if existing.search(text):
        return existing.sub(lambda _m: block, text, count=1)
    head, end = parse_frontmatter_block(text)
    if not head:
        return block + "\n\n" + text.lstrip("\n")
    tail = text[end:].lstrip("\n")
    return head + "\n" + block + "\n\n" + tail


def _strip_dates(s: str) -> str:
    s = re.sub(r"\*\*Updated:\*\* \d{4}-\d{2}-\d{2}", "**Updated:** <date>", s)
    s = re.sub(r'"updated":\s*"\d{4}-\d{2}-\d{2}"', '"updated": "<date>"', s)
    return s


# ----------------------------------------------------------------------------- validation (read-only)


def validate(text: str, lines: list[str], phases: list[Phase]) -> list[str]:
    warnings: list[str] = []
    state_span = _state_line_span(lines)
    for idx, raw in enumerate(lines):
        if state_span[0] <= idx <= state_span[1]:
            continue  # skip the machine state region
        if BARE_CHECKBOX_RE.search(raw) and not PROPER_CHECKBOX_PREFIX_RE.match(raw):
            if re.search(r"(?<!\w)\[[ xX/\-]\](?!\()", raw):
                warnings.append(f"line {idx + 1}: bare checkbox — use '- [ ]', not '{raw.strip()[:60]}'")
    nums = [p.num for p in phases]
    dups = sorted({n for n in nums if nums.count(n) > 1})
    if dups:
        warnings.append(f"duplicate phase number(s): {dups}")
    if nums:
        missing = [n for n in range(min(nums), max(nums) + 1) if n not in nums]
        if missing:
            warnings.append(f"missing phase number(s) in sequence: {missing}")
    fm, _ = parse_frontmatter_block(text)
    if fm:
        po = parse_priority_order(fm)
        nonzero = [p for p in phases if p.num != 0]
        if po and len(po) != len(nonzero):
            warnings.append(
                f"priority_order has {len(po)} item(s) but there are {len(nonzero)} non-zero phase(s) — may have drifted"
            )
    warnings.extend(_validate_toc(lines))
    return warnings


def _state_line_span(lines: list[str]) -> tuple[int, int]:
    start = end = -1
    for i, raw in enumerate(lines):
        if STATE_START in raw:
            start = i
        if STATE_END in raw:
            end = i
    return (start, end) if (start >= 0 and end >= 0) else (10**9, -1)


def _github_slug(title: str) -> str:
    s = title.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = s.replace("_", "")
    return re.sub(r"\s", "-", s)


def _validate_toc(lines: list[str]) -> list[str]:
    slugs: set[str] = set()
    counts: dict[str, int] = {}
    in_toc = False
    toc_links: list[tuple[int, str]] = []
    for idx, raw in enumerate(lines):
        hm = HEADER_RE.match(raw)
        if hm:
            title = hm.group("title")
            if title.strip().lower() == "table of contents":
                in_toc = True
            elif in_toc:
                in_toc = False
            base = _github_slug(title)
            n = counts.get(base, 0)
            slugs.add(base if n == 0 else f"{base}-{n}")
            counts[base] = n + 1
        if in_toc:
            for m in re.finditer(r"\]\(#([^)]+)\)", raw):
                toc_links.append((idx + 1, m.group(1)))
    return [
        f"line {ln}: TOC anchor '#{a}' has no matching header"
        for ln, a in toc_links
        if a not in slugs
    ]


# ----------------------------------------------------------------------------- main


def run(path: str, *, threshold: int, do_stall: bool, seed_from_git: bool, mode: str) -> int:
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()
    lines = text.split("\n")
    today = date.today().isoformat()

    phases = parse_phases(lines)
    metrics = compute_metrics(phases)

    stalled: list[Stall] = []
    blocked: list[Stall] = []
    new_text = text

    if do_stall:
        prior = load_state_blob(text)
        seed = git_seed_dates(path) if seed_from_git else None
        state_tasks = update_state(prior, phases, today, seed)
        stalled, blocked = compute_stalls(phases, metrics, state_tasks, threshold)
        new_text = splice_state_blob(new_text, render_state_blob(state_tasks, today))

    block = render_block(metrics, stalled, blocked, do_stall, threshold)
    new_text = splice_block(new_text, block)

    warnings = validate(text, lines, phases)
    for w in warnings:
        print(f"WARN: {w}", file=sys.stderr)

    if mode == "print":
        print(block)
        return 1 if warnings else 0

    if mode == "check":
        stale = _strip_dates(new_text) != _strip_dates(text)
        if stale:
            print("CHECK: progress/state is out of date — run without --check to update.", file=sys.stderr)
        return 1 if (stale or warnings) else 0

    if new_text != text:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new_text)
        print(f"Updated {path}")
    else:
        print(f"{path} already current")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Generate the progress/stall block + task-state log for a project-plan markdown file.")
    p.add_argument("path", help="Path to the plan markdown file")
    p.add_argument("--threshold", type=int, default=2, help="Stall threshold in business days (default 2)")
    p.add_argument("--no-stall", action="store_true", help="Skip stall logic; leave the state log untouched")
    p.add_argument("--seed-from-git", action="store_true", help="Bootstrap `since` from git blame on first sight of a task")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="Do not write; exit 1 if stale or warnings exist")
    g.add_argument("--print", dest="print_only", action="store_true", help="Print the progress block to stdout; do not write")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    mode = "check" if args.check else "print" if args.print_only else "write"
    return run(
        args.path,
        threshold=args.threshold,
        do_stall=not args.no_stall,
        seed_from_git=args.seed_from_git,
        mode=mode,
    )


if __name__ == "__main__":
    raise SystemExit(main())
