import XCTest
@testable import Focus5Float

/// Covers the Prompt Log tab: parsing the CLIO exporter's Markdown format,
/// pin FIFO eviction/ordering, 200-char truncation, and cold-relaunch
/// persistence for both the selected file and the pin set.
@MainActor
final class PromptLogTests: XCTestCase {
    private static let fileDefaultsKey = "promptLogFilePath"
    private static let pinsDefaultsKey = "pinnedPromptLogIDs"
    private var savedFileDefault: String?
    private var savedPinsDefault: [String]?
    private var tempFiles: [URL] = []

    override func setUp() {
        super.setUp()
        // Isolate from whatever the real app currently has selected/pinned on
        // this machine — restored in tearDown so tests never clobber the
        // user's live Focus5Float state.
        savedFileDefault = UserDefaults.standard.string(forKey: Self.fileDefaultsKey)
        savedPinsDefault = UserDefaults.standard.stringArray(forKey: Self.pinsDefaultsKey)
        UserDefaults.standard.removeObject(forKey: Self.fileDefaultsKey)
        UserDefaults.standard.removeObject(forKey: Self.pinsDefaultsKey)
    }

    override func tearDown() {
        UserDefaults.standard.set(savedFileDefault, forKey: Self.fileDefaultsKey)
        UserDefaults.standard.set(savedPinsDefault, forKey: Self.pinsDefaultsKey)
        for url in tempFiles { try? FileManager.default.removeItem(at: url) }
        tempFiles = []
        super.tearDown()
    }

    private func makeTempFile(named name: String, contents: String) -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("Focus5FloatTests-\(UUID().uuidString)-\(name)")
        try? contents.write(to: url, atomically: true, encoding: .utf8)
        tempFiles.append(url)
        return url
    }

    private func makeRepoCard(repoName: String, localPath: String, vscodeUrl: String) -> RepoCard {
        let json = """
        {"position":1,"repo_name":"\(repoName)","local_path":"\(localPath)","vscode_url":"\(vscodeUrl)",
         "rank_reason":"r","ranking_mode":"recent_activity","computed_at":"2026-01-01T00:00:00Z",
         "ahead":0,"behind":0,"modified_count":0,"untracked_count":0,"is_dirty":false,
         "health_available":true,"recent_activity":[]}
        """
        return try! Focus5JSON.decoder().decode(RepoCard.self, from: Data(json.utf8))
    }

    private func makeOffRosterWarning(repoName: String, localPath: String) -> OffRosterWarning {
        let json = """
        {"repo_name":"\(repoName)","local_path":"\(localPath)",
         "ahead":0,"modified_count":0,"untracked_count":0,"is_dirty":false}
        """
        return try! Focus5JSON.decoder().decode(OffRosterWarning.self, from: Data(json.utf8))
    }

    // MARK: - Parser

    private let twoEntryFixture = """
    # Claude Code Prompt Log

    Generated by CLIO (A member of the rebalanceOS | XYZ | HiQS family)
    https://github.com/Claude-AI-Tools-Ventura-County/clio

    <!-- CLIO:ENTRIES -->

    ## REBALANCE-OS
    2026-07-18T03:09:07Z
    noel's Mac Studio · development

    > "newest prompt"

    ## HYPERCART
    2026-07-09T18:42:11Z
    Noels-MacBook-Pro · main

    > "line one
    > line two"
    """

    func testParsesFieldsAndPreservesNewestFirstOrder() {
        let entries = PromptLogReader.parse(twoEntryFixture)
        XCTAssertEqual(entries.count, 2)
        XCTAssertEqual(entries[0].repo, "REBALANCE-OS")
        XCTAssertEqual(entries[0].timestamp, "2026-07-18T03:09:07Z")
        XCTAssertEqual(entries[0].machine, "noel's Mac Studio")
        XCTAssertEqual(entries[0].branch, "development")
        XCTAssertEqual(entries[0].prompt, "newest prompt")
        XCTAssertEqual(entries[1].repo, "HYPERCART")
        XCTAssertEqual(entries[1].branch, "main")
    }

    func testMultiLinePromptJoinsContinuationLines() {
        let entries = PromptLogReader.parse(twoEntryFixture)
        XCTAssertEqual(entries[1].prompt, "line one\nline two")
    }

    func testMissingBranchYieldsNilBranch() {
        let fixture = """
        <!-- CLIO:ENTRIES -->

        ## SOLO-REPO
        2026-07-01T00:00:00Z
        somehost

        > "no branch here"
        """
        let entries = PromptLogReader.parse(fixture)
        XCTAssertEqual(entries.count, 1)
        XCTAssertEqual(entries[0].machine, "somehost")
        XCTAssertNil(entries[0].branch)
    }

    func testTextWithoutMarkerStillParses() {
        // A pre-marker legacy file (no `<!-- CLIO:ENTRIES -->`) — the reader
        // falls back to scanning the whole text rather than returning nothing.
        let fixture = """
        ## LEGACY
        2026-01-01T00:00:00Z
        host · main

        > "still parseable"
        """
        let entries = PromptLogReader.parse(fixture)
        XCTAssertEqual(entries.count, 1)
        XCTAssertEqual(entries[0].prompt, "still parseable")
    }

    func testMixedLegacyAndContentIDEntriesIgnoreHTMLComments() {
        let fixture = """
        <!-- CLIO:ENTRIES -->

        <!-- clio:id:new-session:2026-07-19T12:00:00Z -->
        ## NEW-FORMAT
        2026-07-19T12:00:00Z
        new-host · development

        > "content-addressed prompt"

        ## LEGACY-FORMAT
        2026-07-18T11:00:00Z
        legacy-host · main

        > "legacy prompt"
        """

        let entries = PromptLogReader.parse(fixture)
        XCTAssertEqual(entries.count, 2)
        XCTAssertEqual(
            entries[0],
            PromptLogEntry(
                repo: "NEW-FORMAT",
                timestamp: "2026-07-19T12:00:00Z",
                machine: "new-host",
                branch: "development",
                prompt: "content-addressed prompt"
            )
        )
        XCTAssertEqual(
            entries[1],
            PromptLogEntry(
                repo: "LEGACY-FORMAT",
                timestamp: "2026-07-18T11:00:00Z",
                machine: "legacy-host",
                branch: "main",
                prompt: "legacy prompt"
            )
        )
        for entry in entries {
            XCTAssertFalse(entry.repo.contains("clio:id"))
            XCTAssertFalse(entry.timestamp.contains("clio:id"))
            XCTAssertFalse(entry.prompt.contains("clio:id"))
        }
    }

    func testMachineNoiseEntriesAreFilteredOut() {
        let fixture = """
        <!-- CLIO:ENTRIES -->

        ## REBALANCE-OS
        2026-07-18T00:00:00Z
        host · main

        > "<task-notification>
        > <task-id>abc123</task-id>
        > <status>completed</status>
        > </task-notification>"

        ## XYZ-3-AGENTS-SWARM
        2026-07-18T00:01:00Z
        host · main

        > "[cross-agent dependency drift — informational, warn-only; re-check if your task depends on these]
        > - agy changed relay-automation/relay-turn-lib.sh (0 lines) since your last turn."

        ## HYPERCART
        2026-07-18T00:02:00Z
        host · main

        > "real prompt about the checkout flow"
        """
        let entries = PromptLogReader.parse(fixture)
        XCTAssertEqual(entries.count, 1)
        XCTAssertEqual(entries[0].repo, "HYPERCART")
        XCTAssertEqual(entries[0].prompt, "real prompt about the checkout flow")
    }

    func testPromptStartingWithBracketedRealTextIsNotFilteredIfNotMachineWrapper() {
        // Only the specific `<...>` / `[...]` wrapper shapes are noise; a
        // genuine prompt happening to start with a bracket-like character is
        // NOT the target of this filter, but per the current shape-based
        // heuristic it IS excluded too — documenting that known trade-off
        // rather than silently accepting it.
        let fixture = """
        <!-- CLIO:ENTRIES -->

        ## HYPERCART
        2026-07-18T00:00:00Z
        host · main

        > "[urgent] please fix the checkout bug"
        """
        let entries = PromptLogReader.parse(fixture)
        XCTAssertTrue(entries.isEmpty)   // known trade-off: bracket-prefixed real prompts are also hidden
    }

    func testEmptyOrMarkerOnlyTextParsesToNoEntries() {
        XCTAssertTrue(PromptLogReader.parse("").isEmpty)
        XCTAssertTrue(PromptLogReader.parse("<!-- CLIO:ENTRIES -->\n").isEmpty)
    }

    // MARK: - Bounded load (large-file safety)

    /// Builds a CLIO note with `count` entries, newest-first, repo names REPO0
    /// (newest) … REPO<count-1> (oldest) — mirroring how CLIO prepends.
    private func makeLog(entryCount count: Int) -> String {
        var s = "<!-- CLIO:ENTRIES -->\n\n"
        for i in 0..<count {
            s += "## REPO\(i)\n2026-07-18T00:00:00Z\nmachine · main\n\n> \"prompt \(i)\"\n\n"
        }
        return s
    }

    func testLoadCapsAtRowCapKeepingNewest() {
        let url = makeTempFile(named: "many.md", contents: makeLog(entryCount: 5))
        let entries = PromptLogReader.load(from: url, rowCap: 3)
        XCTAssertEqual(entries?.count, 3)
        // Newest-first, so the cap keeps REPO0..REPO2 and drops the oldest tail.
        XCTAssertEqual(entries?.map(\.repo), ["REPO0", "REPO1", "REPO2"])
    }

    func testLoadTruncatesAtByteCeilingDroppingOldestTail() {
        let log = makeLog(entryCount: 40)
        let url = makeTempFile(named: "big.md", contents: log)
        // Ceiling that lands partway through the file: the newest entries (top)
        // survive; an entry known to sit beyond the cutoff must be gone.
        let ceiling = log.utf8.count / 2
        let entries = PromptLogReader.load(from: url, byteCeiling: ceiling)
        let repos = entries?.map(\.repo) ?? []
        XCTAssertTrue(repos.contains("REPO0"), "newest entry (top of file) must survive truncation")
        XCTAssertFalse(repos.contains("REPO39"), "oldest entry (past the byte ceiling) must be dropped")
        XCTAssertLessThan(repos.count, 40, "truncation must drop some entries")
    }

    func testLoadReturnsNilForMissingFile() {
        let missing = FileManager.default.temporaryDirectory
            .appendingPathComponent("Focus5FloatTests-does-not-exist-\(UUID().uuidString).md")
        XCTAssertNil(PromptLogReader.load(from: missing))
    }

    // MARK: - Truncation

    func testPromptUnder200CharsIsNotTruncated() {
        let entry = PromptLogEntry(repo: "R", timestamp: "T", machine: "M", branch: nil, prompt: "short")
        XCTAssertEqual(entry.truncatedPrompt, "short")
    }

    func testPromptOver200CharsIsTruncatedWithEllipsis() {
        let long = String(repeating: "a", count: 250)
        let entry = PromptLogEntry(repo: "R", timestamp: "T", machine: "M", branch: nil, prompt: long)
        XCTAssertEqual(entry.truncatedPrompt.count, 201)   // 200 chars + ellipsis
        XCTAssertTrue(entry.truncatedPrompt.hasSuffix("…"))
        XCTAssertEqual(String(entry.truncatedPrompt.dropLast()), String(long.prefix(200)))
    }

    // MARK: - Pin FIFO

    func testPinningAddsToFrontUpToFive() {
        let model = Focus5Model()
        let entries = (0..<5).map { PromptLogEntry(repo: "R", timestamp: "T\($0)", machine: "M", branch: nil, prompt: "p\($0)") }
        for e in entries { model.togglePin(e) }

        // Newest pin (last one pinned) is at the front.
        XCTAssertEqual(model.pinnedPromptLogIDs, entries.reversed().map(\.id))
    }

    func testPinningASixthEvictsTheOldestPin() {
        let model = Focus5Model()
        let entries = (0..<6).map { PromptLogEntry(repo: "R", timestamp: "T\($0)", machine: "M", branch: nil, prompt: "p\($0)") }
        for e in entries { model.togglePin(e) }

        XCTAssertEqual(model.pinnedPromptLogIDs.count, 5)
        XCTAssertFalse(model.pinnedPromptLogIDs.contains(entries[0].id))   // oldest pin evicted
        XCTAssertEqual(model.pinnedPromptLogIDs.first, entries[5].id)      // newest pin at front
    }

    func testTogglingAnAlreadyPinnedEntryUnpinsIt() {
        let model = Focus5Model()
        let entry = PromptLogEntry(repo: "R", timestamp: "T", machine: "M", branch: nil, prompt: "p")
        model.togglePin(entry)
        XCTAssertTrue(model.isPinned(entry))
        model.togglePin(entry)
        XCTAssertFalse(model.isPinned(entry))
    }

    func testResetAllClearsPins() {
        let model = Focus5Model()
        let entry = PromptLogEntry(repo: "R", timestamp: "T", machine: "M", branch: nil, prompt: "p")
        model.togglePin(entry)
        XCTAssertFalse(model.pinnedPromptLogIDs.isEmpty)
        model.resetAllPromptLogPins()
        XCTAssertTrue(model.pinnedPromptLogIDs.isEmpty)
    }

    func testPinnedAndUnpinnedEntriesPartitionWithoutOverlap() {
        let model = Focus5Model()
        model.promptLogFileURL = makeTempFile(named: "log.md", contents: twoEntryFixture)
        let toPin = model.promptLogEntries[0]
        model.togglePin(toPin)

        XCTAssertEqual(model.pinnedPromptLogEntries.map(\.id), [toPin.id])
        XCTAssertFalse(model.unpinnedPromptLogEntries.map(\.id).contains(toPin.id))
        XCTAssertEqual(model.unpinnedPromptLogEntries.count, model.promptLogEntries.count - 1)
    }

    // MARK: - Persistence

    func testFileSelectionAndPinsPersistAcrossModelRelaunch() {
        let url = makeTempFile(named: "log.md", contents: twoEntryFixture)
        let first = Focus5Model()
        first.promptLogFileURL = url
        let entry = first.promptLogEntries[0]
        first.togglePin(entry)

        let relaunched = Focus5Model()
        XCTAssertEqual(relaunched.promptLogFileURL, url)
        XCTAssertEqual(relaunched.pinnedPromptLogIDs, [entry.id])
    }

    func testMissingFileReportsLoadError() {
        let model = Focus5Model()
        model.promptLogFileURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("gone-\(UUID().uuidString).md")
        XCTAssertNotNil(model.promptLogLoadError)
        XCTAssertTrue(model.promptLogEntries.isEmpty)
    }

    func testClearingSelectionResetsState() {
        let model = Focus5Model()
        model.promptLogFileURL = makeTempFile(named: "log.md", contents: twoEntryFixture)
        XCTAssertFalse(model.promptLogEntries.isEmpty)

        model.promptLogFileURL = nil
        XCTAssertTrue(model.promptLogEntries.isEmpty)
        XCTAssertNil(model.promptLogLoadError)
    }

    // MARK: - "Open in VS Code" resolution

    func testVscodeOpenInfoResolvesFromRoster() {
        let model = Focus5Model()
        model.roster = [makeRepoCard(repoName: "rebalance-OS", localPath: "/repos/rebalance-OS", vscodeUrl: "vscode://file/repos/rebalance-OS")]

        let info = model.vscodeOpenInfo(forRepoName: "REBALANCE-OS")   // CLIO logs repo names upper-cased
        XCTAssertEqual(info?.localPath, "/repos/rebalance-OS")
        XCTAssertEqual(info?.vscodeURL, "vscode://file/repos/rebalance-OS")
    }

    func testVscodeOpenInfoFallsBackToOffRosterAndDerivesURL() {
        let model = Focus5Model()
        model.offRoster = [makeOffRosterWarning(repoName: "hypercart", localPath: "/repos/hypercart")]

        let info = model.vscodeOpenInfo(forRepoName: "HYPERCART")
        XCTAssertEqual(info?.localPath, "/repos/hypercart")
        XCTAssertEqual(info?.vscodeURL, "vscode://file/repos/hypercart")   // derived, OffRosterWarning has no vscodeUrl field
    }

    func testVscodeOpenInfoIsNilForAnUnknownRepo() {
        let model = Focus5Model()
        model.roster = [makeRepoCard(repoName: "rebalance-OS", localPath: "/repos/rebalance-OS", vscodeUrl: "vscode://file/repos/rebalance-OS")]

        XCTAssertNil(model.vscodeOpenInfo(forRepoName: "SOME-OTHER-REPO"))
    }
}
