"""DASHBOARD.md generation for 3-Eyes (GH-195).

The committed ``DASHBOARD.md`` is a DETERMINISTIC projection of the TOML registry —
same registry in, byte-identical markdown out. That determinism is what lets three
redundant triggers keep it honest:

  * CLI ``sync-dashboard`` rewrites it on any registry mutation,
  * the ``hooks/regen-dashboard`` pre-commit hook regenerates + stages it, and
  * ``dashboard.py --check`` fails CI when the committed file drifts from a fresh
    render.

Because it must be reproducible in CI (where no launchd agents exist), the
committed file mirrors the *registry* only — the static "what jobs exist and how
they are configured". The volatile launchctl run-state overlay ("loaded right
now?") is a separate CLI/MCP query (:func:`render_live`), never baked into the
file. A short content fingerprint (a hash of the source TOML) gives an at-a-glance
"did the registry change?" signal without embedding a volatile timestamp that
would defeat ``--check``.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

from . import config, launchd, registry

BANNER = "<!-- GENERATED by `python -m three_eyes sync-dashboard` from registry/*.toml. DO NOT EDIT BY HAND. -->"


def _fingerprint(registry_dir: Path) -> str:
    """Stable hash of every registry source file — deterministic across machines."""
    h = hashlib.sha256()
    parts: list[Path] = sorted((registry_dir / "jobs.d").glob("*.toml"))
    for extra in ("commands.allow", "routes.toml"):
        p = registry_dir / extra
        if p.exists():
            parts.append(p)
    for path in parts:
        h.update(path.name.encode())
        h.update(b"\0")
        h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:12]


def _fmt_breakers(job) -> str:
    bits = []
    if job.single_instance:
        bits.append("single-instance")
    if job.max_rss_gb:
        bits.append(f"≤{job.max_rss_gb:g}GB")
    if job.trip_after_failures:
        bits.append(f"trip@{job.trip_after_failures}")
    return ", ".join(bits) or "—"


def render(registry_dir: Path | None = None) -> str:
    """Render DASHBOARD.md content deterministically from the registry."""
    registry_dir = registry_dir or config.REGISTRY_DIR
    # Committed-only (include_local=False): DASHBOARD.md is the fleet-portable mirror
    # of the checked-in registry, so a machine-local job never drifts it across clones.
    jobs = registry.load_jobs(registry_dir, include_local=False)
    problems = registry.validate(registry_dir, include_local=False)
    fp = _fingerprint(registry_dir)

    lines = [
        BANNER,
        "",
        "# 3-Eyes — job dashboard",
        "",
        "One optional, always-safe local job supervisor (GH-195). This file is a "
        "generated mirror of the TOML registry — **the jobs below are exactly what "
        "`registry/jobs.d/*.toml` declares.**",
        "",
        f"- **Registry fingerprint:** `{fp}`",
        f"- **Jobs defined:** {len(jobs)}",
        f"- **Registry valid:** {'✅ yes' if not problems else '❌ NO — see below'}",
        "- **Full machine inventory** (managed + observe-only + to-adopt): `CATALOG.md` — generated "
        "(gitignored, machine-specific) from `registry/catalog-notes.toml`; run `python -m three_eyes "
        "catalog --write`. Fleet health: `python -m three_eyes health`.",
        "",
        "> Inert by default: with no `config/runtime.env` (or `THREE_EYES_ENABLE!=1`) "
        "none of these jobs run — 3-Eyes makes zero network / launchd / cron calls. "
        "Live load-state (`loaded right now?`) is a `python -m three_eyes status` query, "
        "not shown here.",
        "",
    ]

    if problems:
        lines += ["## ⚠️ Registry problems", ""]
        lines += [f"- {p}" for p in problems]
        lines += [""]

    lines += [
        "## Jobs",
        "",
        "| Job | Enabled | Schedule | Command | Routes | Breakers | Relief |",
        "|-----|---------|----------|---------|--------|----------|--------|",
    ]
    for job in jobs:
        relief = job.relief or {}
        relief_s = (
            f"llm {relief.get('llm_per_run_max', '—')}/run, {relief.get('llm_daily_max', '—')}/day"
            if relief else "—"
        )
        routes_s = ", ".join(job.routes) or "—"
        lines.append(
            f"| `{job.id}` | {'yes' if job.enabled else 'no'} | {job.schedule_summary()} "
            f"| `{job.command}` | {routes_s} | {_fmt_breakers(job)} | {relief_s} |"
        )
    if not jobs:
        lines.append("| _(none)_ | | | | | | |")
    lines += [
        "",
        "## Descriptions",
        "",
    ]
    for job in jobs:
        lines.append(f"- **`{job.id}`** — {job.description or '_(no description)_'}")
    if not jobs:
        lines.append("_(no jobs defined yet)_")
    lines.append("")
    return "\n".join(lines)


def write(registry_dir: Path | None = None, dashboard_path: Path | None = None) -> Path:
    """Regenerate and write DASHBOARD.md. Returns the path written."""
    path = dashboard_path or config.DASHBOARD
    path.write_text(render(registry_dir))
    return path


def check(registry_dir: Path | None = None, dashboard_path: Path | None = None) -> bool:
    """True when the committed DASHBOARD.md matches a fresh render (no drift)."""
    path = dashboard_path or config.DASHBOARD
    try:
        current = path.read_text()
    except OSError:
        return False
    return current == render(registry_dir)


def render_live(registry_dir: Path | None = None) -> str:
    """Registry ⋈ live launchctl state — for the CLI/MCP, NOT the committed file."""
    jobs = registry.load_jobs(registry_dir)
    lines = ["Job                         Schedule                 Live"]
    for job in jobs:
        state = launchd.launchctl_state(launchd.plist_label(job.id))
        lines.append(f"{job.id:<27} {job.schedule_summary():<24} {state}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="three_eyes.dashboard")
    parser.add_argument("--check", action="store_true", help="fail if DASHBOARD.md is stale")
    parser.add_argument("--write", action="store_true", help="regenerate DASHBOARD.md")
    args = parser.parse_args(argv)
    if args.check:
        if check():
            print("DASHBOARD.md is current.")
            return 0
        print("DASHBOARD.md is STALE — run `python -m three_eyes sync-dashboard`.", file=sys.stderr)
        return 1
    if args.write:
        path = write()
        print(f"wrote {path}")
        return 0
    print(render())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
