import * as assert from 'assert';
import { parsePulseMarkdown } from '../pulseParser';

/**
 * Fixture grounded in a real `live-pulse.md` on-disk sample from this
 * device (`~/git-pulse-sync/live-pulse.md`, generated by
 * `render_pulse_markdown()`), with synthetic-but-format-accurate bullet
 * lines added for Upcoming Meetings / Assigned Issues since this device's
 * real file happened to have both empty on the day it was captured. The
 * bullet shapes below match the patterns documented in the GH-123 spike
 * findings (bold time range for meetings; backtick-repo + markdown-link
 * for issues).
 */
const FIXTURE = `# Live Pulse — Thursday, July 16, 2026
_Last updated: 10:00 PM PDT (America/Los_Angeles) for \`tester\`_

## Current Day

### What I've been working on
**Issues / PRs created or updated** (1 — 1 🤖cloud-claude)
- \`🤖cloud-claude\` NEW \`NeochromeTeam/sleuth-app\` [pull_request #398](https://github.com/NeochromeTeam/sleuth-app/pull/398) (closed) — GH-395 + GH-396: infer client-name prefix on tasks, fed by operator-managed clients overlay

**Obsidian vault edits**
- HQ MARATHON — 2026-07-17 (\`XYZ - HQ Global Marathon.md\`) — 8:18 PM
- 0. Today's Notes (\`0. Today's Notes.md\`) — 6:00 PM

### Watched repos (external activity)
_No external/watched-repo activity today._

### Upcoming Meetings
- **5:00 PM–5:15 PM** — End of Day Check-In
- **9:00 AM–9:30 AM** — Weekly Sync @ Zoom

### GitHub Issues assigned to me (last 7 days)
- \`Hypercart-Dev-Tools/pdda\` [#15](https://github.com/Hypercart-Dev-Tools/pdda/issues/15) — Fix flaky preflight retry _(updated Jul 8 8:13 PM)_
- **NEW** \`Hypercart-Dev-Tools/rebalance-OS\` [#123](https://github.com/Hypercart-Dev-Tools/rebalance-OS/issues/123) — VS Code extension tree view _(updated Jul 16 3:00 PM)_

### Sleuth (Slack) reminders assigned to/by me
_No active reminders touched today._

## Yesterday

### What I worked on yesterday
**Issues/PRs touched:** 1
- \`BinoidCBD/LTVera-Pandas\` [pull_request #54](https://github.com/BinoidCBD/LTVera-Pandas/pull/54) — GH-52: fix 3 data bugs + turn down cost/cadence dials
**Vault edits:** 1 files
- Cactus Pdda Log (\`Cactus - PDDA Log.md\`)
`;

describe('pulseParser', () => {
  it('buckets lines into the 4 tracked sections', () => {
    const parsed = parsePulseMarkdown(FIXTURE);

    assert.ok(parsed.today.rawLines.length > 0, 'today section should have lines');
    assert.ok(parsed.yesterday.rawLines.length > 0, 'yesterday section should have lines');
    assert.ok(parsed.upcomingMeetings.rawLines.length > 0, 'upcomingMeetings section should have lines');
    assert.ok(parsed.assignedIssues.rawLines.length > 0, 'assignedIssues section should have lines');
  });

  it('does not leak an untracked section (Watched repos) into a tracked one', () => {
    const parsed = parsePulseMarkdown(FIXTURE);
    const allText = [
      ...parsed.today.rawLines,
      ...parsed.yesterday.rawLines,
      ...parsed.upcomingMeetings.rawLines,
      ...parsed.assignedIssues.rawLines,
    ].join('\n');
    assert.ok(!allText.includes('No external/watched-repo activity'));
    assert.ok(!allText.includes('No active reminders touched today'));
  });

  it('parses Today bullets, including the group-label sub-headers', () => {
    const parsed = parsePulseMarkdown(FIXTURE);
    const groupLabels = parsed.today.items.filter((i) => i.isGroupLabel).map((i) => i.text);
    assert.ok(groupLabels.some((t) => t.startsWith('**Issues / PRs created or updated**')));
    assert.ok(groupLabels.some((t) => t.startsWith('**Obsidian vault edits**')));

    const bullets = parsed.today.items.filter((i) => !i.isGroupLabel);
    assert.ok(bullets.some((i) => i.text.includes('sleuth-app')));
    assert.ok(bullets.some((i) => i.text.includes("Today's Notes")));
  });

  it('parses Yesterday bullets', () => {
    const parsed = parsePulseMarkdown(FIXTURE);
    assert.ok(parsed.yesterday.items.some((i) => i.text.includes('LTVera-Pandas')));
    assert.ok(parsed.yesterday.items.some((i) => i.text.includes('Cactus - PDDA Log')));
  });

  it('parses Upcoming Meetings bullets (bold time range + em-dash summary)', () => {
    const parsed = parsePulseMarkdown(FIXTURE);
    assert.strictEqual(parsed.upcomingMeetings.items.length, 2);
    assert.ok(parsed.upcomingMeetings.items[0].text.includes('End of Day Check-In'));
    assert.ok(parsed.upcomingMeetings.items[1].text.includes('Weekly Sync'));
    assert.ok(parsed.upcomingMeetings.items.every((i) => !i.isPlaceholder));
  });

  it('parses Assigned Issues bullets (backtick repo + markdown link + italic timestamp)', () => {
    const parsed = parsePulseMarkdown(FIXTURE);
    assert.strictEqual(parsed.assignedIssues.items.length, 2);
    assert.ok(parsed.assignedIssues.items[0].text.includes('Fix flaky preflight retry'));
    assert.ok(parsed.assignedIssues.items[1].text.includes('VS Code extension tree view'));
  });

  it('recognizes italic empty-state placeholder lines', () => {
    const emptyFixture = `## Current Day

### Upcoming Meetings
_No upcoming meetings today._

### GitHub Issues assigned to me (last 7 days)
_No open issues assigned in the last 7 days._
`;
    const parsed = parsePulseMarkdown(emptyFixture);
    assert.strictEqual(parsed.upcomingMeetings.items.length, 1);
    assert.strictEqual(parsed.upcomingMeetings.items[0].isPlaceholder, true);
    assert.strictEqual(parsed.assignedIssues.items.length, 1);
    assert.strictEqual(parsed.assignedIssues.items[0].isPlaceholder, true);
  });

  it('returns empty sections (not a throw) for an empty or unrelated document', () => {
    const parsed = parsePulseMarkdown('# Some other document\n\nNo pulse sections here.\n');
    assert.strictEqual(parsed.today.items.length, 0);
    assert.strictEqual(parsed.yesterday.items.length, 0);
    assert.strictEqual(parsed.upcomingMeetings.items.length, 0);
    assert.strictEqual(parsed.assignedIssues.items.length, 0);
  });

  it('does not throw on a completely empty string', () => {
    assert.doesNotThrow(() => parsePulseMarkdown(''));
  });
});
